### ISSUE TITLE
Error with “model = PromptCap("vqascore/promptcap-coco-vqa")”

### ISSUE THREAD

**Issue by cmcv2022** [Yushi-Hu/PromptCap#5]
Hello, I encountered the following error while using this interface. Is it not working?

vqascore/promptcap-coco-vqa
<super: <class 'OFATokenizer'>, <OFATokenizer object>>
Traceback (most recent call last):
  File "/home/lh/mukea-clip/pc.py", line 4, in <module>
    model = PromptCap("vqascore/promptcap-coco-vqa")  # also support OFA checkpoints. e.g. "OFA-Sys/ofa-large"
  File "/home/lh/.conda/envs/pytorch/lib/python3.6/site-packages/promptcap/promptcap.py", line 12, in __init__
    self.tokenizer = OFATokenizer.from_pretrained(ckpt)
  File "/home/lh/.conda/envs/pytorch/lib/python3.6/site-packages/promptcap/tokenization_ofa.py", line 67, in from_pretrained
    tokenizer = super().from_pretrained(pretrained_model_name_or_path, *init_inputs, **kwargs)
  File "/home/lh/.conda/envs/pytorch/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1664, in from_pretrained
    local_files_only=local_files_only,
  File "/home/lh/.conda/envs/pytorch/lib/python3.6/site-packages/transformers/file_utils.py", line 2242, in get_file_from_repo
    use_auth_token=use_auth_token,
  File "/home/lh/.conda/envs/pytorch/lib/python3.6/site-packages/transformers/file_utils.py", line 1854, in cached_path
    local_files_only=local_files_only,
  File "/home/lh/.conda/envs/pytorch/lib/python3.6/site-packages/transformers/file_utils.py", line 2103, in get_from_cache
    "Connection error, and we cannot find the requested files in the cached path."
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

**Comment by Yushi-Hu** [comment]
Sorry for the late reply! We renamed our repo and that is causing the problem. Please try "tifa-benchmark/promptcap-coco-vqa"
